select * from customers;

-- Q1. What is the total revenue generated by male vs female?
Select gender, sum(purchase_amount) AS REVENUE
From customers
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customers
WHERE discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customers);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, round(AVG(review_rating),2)
FROM customers
group by item_purchased
order by AVG(review_rating) DESC
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type, ROUND(avg(purchase_amount),2)
FROM customers
WHERE shipping_type IN ( "Express" ,"Standard")
GROUP BY shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.

SELECT subscription_status,
count(customer_id) as total_customers,
 sum(purchase_amount) AS total_revenue ,
 round(AVG(purchase_amount),2) AS avg_spend
FROM customers
GROUP BY subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied? 
-- Why did we use CASE?
-- Because SQL: Cannot directly “count Yes only”
-- So we convert Yes → 1, No → 0, Then sum them

SELECT item_purchased, 
round(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END )/COUNT(*) * 100,2) AS discount_rate
FROM customers
GROUP BY item_purchased
ORDER BY discount_rate desc
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with customer_type as (
select customer_id, previous_purchases,
CASE 
 WHEN previous_purchases = 1 THEN 'New'
  WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
   ELSE 'Loyal'
   END AS customer_segment
   FROM customers
)

SELECT customer_segment, COUNT(customer_segment)
from customer_type
group by customer_segment;


-- Q8. What are the top 3 most purchased products within each category? 
with item_count as (
select category, item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rank
from customers
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_count
where item_rank <=3;

 
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers
from customers
where previous_purchases > 5
group by subscription_status;



-- Q10. What is the revenue contribution of each age group? 
select age_group, sum(purchase_amount) as total_Revenue
from customers
group by age_group
order by total_Revenue desc;
 